general.import = ["colours.toml"]

[window]

dimensions.columns = 127
dimensions.lines = 27

title = "Alacritty"
dynamic_title = false

opacity = 0.5

padding.x = 10
padding.y = 10

decorations = "None"
decorations_theme_variant = "Dark"

[font]

normal.family = "JetBrainsMono Nerd Font"

size = 10.0

[cursor]

blink_interval = 600
unfocused_hollow = true

[cursor.style]

shape   = "Beam"
blinking= "Always"

[mouse]

hide_when_typing = true

[keyboard]

bindings = [
    { key = "N", mods = "Control", action = "CreateNewWindow" },
]
